#ifndef QT_DATA_TEST_REPOSITORY_SQLITE_GLOBAL_H
#define QT_DATA_TEST_REPOSITORY_SQLITE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT_DATA_TEST_REPOSITORY_SQLITE_LIBRARY)
#define QT_DATA_TEST_REPOSITORY_SQLITE_EXPORT Q_DECL_EXPORT
#else
#define QT_DATA_TEST_REPOSITORY_SQLITE_EXPORT Q_DECL_IMPORT
#endif

#endif // QT_DATA_TEST_REPOSITORY_SQLITE_GLOBAL_H
